### ISSUE TITLE
V. 0.3.1 no french translation for me

### ISSUE THREAD

**Issue by gbdomubpkm** [mateosalta/uvolman-fork#14]
Hi.
I don't see the french translation..

**Comment by mateosalta** [comment]
hm, strange. seems it is not picking up the translation

**Comment by mateosalta** [comment]
[uvolman.mateosalta_0.3.2_armhf.zip](https://github.com/mateosalta/uvolman-fork/files/4304197/uvolman.mateosalta_0.3.2_armhf.zip)

**Comment by mateosalta** [comment]
Thank you, had no idea they were broken for so long :)

**Comment by gbdomubpkm** [comment]
Fixed for French (even if everything is not translated).
Close if you think it's good.

**Comment by gbdomubpkm** [comment]
Hi @Anne017 I love your work. It would be really great if you could take some time to update the French translation of this great and essential app. Some strings are not translated. Regards.

**Comment by Anne017** [comment]
Hi @gbdomubpkm , all translatable strings are currently already translated.
After testing on my own device, the only strings not translated are things like "sink-input-by-media-role:phone". Do you confirm?
If yes, it requires a modification of the Main.qml file by @mateosalta to allow internationalization (i18n.tr() addition), then an update of the .pot file (note the po folder contains two .pot files, most probably coming from the app fork, when only one would be the best practice).

**Comment by gbdomubpkm** [comment]
Thanks for your quick answer @Anne017 
I confirm what you say.
Strings not french translated are 
- sink-input-by-media-role-phone
- sink-input-by-media-role-alert
- sink-input-by-media-role-multimedia
- sink-input-by-media-role-alarm

And also
- warning-volume-enabled
- allow-amplified-volume

**Comment by mateosalta** [comment]
the problem with the sinks is that those are directly determined by the pulse input names, i need to have it somehow hide those and insdead display a translarable device name.

**Comment by mateosalta** [comment]
the last two should be translatable, although the english was chosen with dashes to match the gsettings valuse
